//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.7.0
//     from Assets/CPRInputActions.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @CPRInputActions: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @CPRInputActions()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""CPRInputActions"",
    ""maps"": [
        {
            ""name"": ""CPRControls"",
            ""id"": ""15d9f1e1-7afa-43f5-bc50-54ad17ee8eef"",
            ""actions"": [
                {
                    ""name"": ""PumpAction"",
                    ""type"": ""Button"",
                    ""id"": ""401d07c5-15f4-440b-a267-1936ff2511c0"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""15ee2d78-a873-490a-bbd7-77c641e32d01"",
                    ""path"": ""<Keyboard>/anyKey"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PumpAction"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e5de4edb-4498-4cf6-a34f-59337c3cf186"",
                    ""path"": ""<Gamepad>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PumpAction"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // CPRControls
        m_CPRControls = asset.FindActionMap("CPRControls", throwIfNotFound: true);
        m_CPRControls_PumpAction = m_CPRControls.FindAction("PumpAction", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // CPRControls
    private readonly InputActionMap m_CPRControls;
    private List<ICPRControlsActions> m_CPRControlsActionsCallbackInterfaces = new List<ICPRControlsActions>();
    private readonly InputAction m_CPRControls_PumpAction;
    public struct CPRControlsActions
    {
        private @CPRInputActions m_Wrapper;
        public CPRControlsActions(@CPRInputActions wrapper) { m_Wrapper = wrapper; }
        public InputAction @PumpAction => m_Wrapper.m_CPRControls_PumpAction;
        public InputActionMap Get() { return m_Wrapper.m_CPRControls; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(CPRControlsActions set) { return set.Get(); }
        public void AddCallbacks(ICPRControlsActions instance)
        {
            if (instance == null || m_Wrapper.m_CPRControlsActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_CPRControlsActionsCallbackInterfaces.Add(instance);
            @PumpAction.started += instance.OnPumpAction;
            @PumpAction.performed += instance.OnPumpAction;
            @PumpAction.canceled += instance.OnPumpAction;
        }

        private void UnregisterCallbacks(ICPRControlsActions instance)
        {
            @PumpAction.started -= instance.OnPumpAction;
            @PumpAction.performed -= instance.OnPumpAction;
            @PumpAction.canceled -= instance.OnPumpAction;
        }

        public void RemoveCallbacks(ICPRControlsActions instance)
        {
            if (m_Wrapper.m_CPRControlsActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(ICPRControlsActions instance)
        {
            foreach (var item in m_Wrapper.m_CPRControlsActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_CPRControlsActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public CPRControlsActions @CPRControls => new CPRControlsActions(this);
    public interface ICPRControlsActions
    {
        void OnPumpAction(InputAction.CallbackContext context);
    }
}
